### ISSUE TITLE
Problem with LoggingMiddleware in combination with QueuedCommandMiddleware

### ISSUE THREAD

**Issue by Bhoft** [trntv/yii2-command-bus#12]
Hi there is a problem with the logging mechanism in combination with QueuedCommandMiddleware.
The problem is the default Logger has a flush Interval of 1000.
http://www.yiiframework.com/doc-2.0/yii-log-logger.html#$flushInterval-detail

So only after 1000 logs logs like 

```
Yii::getLogger()->log("Command execution started: {$class}", $this->level, $this->category);"
```

would be written to the log when a QueuedCommandMiddleware is used. Because the Process doesn't stop so the logger isn't flushed at the end.

Also there should be mentioned that if you want a logging mechanism almost realtime you also have to set the `'exportInterval' => 1,`  in your log target.

http://www.yiiframework.com/doc-2.0/yii-log-target.html#$exportInterval-detail

Otherwise also after 1000 log messages the log would be really written.

There should also be a flush added after each Logger::log call in the LoggingMiddleware.

**Comment by trntv** [comment]
Maabe we should add flushInterval property to LoggingMiddleware and set Logger::flushInterval at runtime rather that force flush?
It will add more control over logging process to end user.

**Comment by Bhoft** [comment]
If a manual flush is done the `flushinterval` seams not to be important. 
But the `exportInterval` must be set.
I haven't tested if its can be set dynamically and reset afterwards.

Anyhow if I have a log setting only for the command-bus I think its not a problem to set the setting in the config and do a flush on start and end of the process.

If the command logs as well he has to flush manually, otherwise he will get his logs only after 1000 entries or after the command is fully processed.

```
 [
         'class' => 'yii\log\FileTarget',
                    'categories' => ['command-bus'],
                    'logFile' => '@app/runtime/logs/command-bus.log',
                    'logVars' => [],
                   'exportInterval' => 1, // log Immediate 
],
```
