### ISSUE TITLE
Issue with PHP_BINARY

### ISSUE THREAD

**Issue by odannyc** [trntv/yii2-command-bus#18]
I'm running PHP-FPM on my server, so when I try and use this commandbus library with the background async process it never actually runs anything because the PHP_BINARY is set to "php-fpm" and php doesn't run commands on that. Any ideas?

**Comment by odannyc** [comment]
PR for this issue is #19

**Comment by trntv** [comment]
Why not to set `backgroundHandlerBinary` manually? This should solve your problem.

**Comment by odannyc** [comment]
@trntv 

That shouldn't be a solution since this should do its best to determine what php binary to use dynamically.
Also, since I'm going between different environments, prod, staging, ci, dev.. the binary might change. Also my co workers are probably using a different environment than I am so hard coding the variable should not be a solution.

The PR I submitted should take care of all these problems.

**Comment by odannyc** [comment]
@trntv any updates on this?

**Comment by trntv** [comment]
To be honest, i don't like any kind of programming "magic" this one is a kind of it. I still think that if you can provide binary path by configuration you should do it. You can extend this middleware manually, run your magic when initializing command bus etc.
