### ISSUE TITLE
Object can not be specific class name

### ISSUE THREAD

**Issue by mpirogov** [trntv/yii2-command-bus#24]
Can you fix this issue?

**Comment by mpirogov** [comment]
I have forked yours.

**Comment by mpirogov** [comment]
https://github.com/Mpirogov/yii2-command-bus

**Comment by mpirogov** [comment]
can I merge my code with yours?

**Comment by mpirogov** [comment]
I have fixed it myself.

**Comment by mpirogov** [comment]
https://github.com/trntv/yii2-command-bus/issues/22

**Comment by mpirogov** [comment]
it is dumplicate issue

**Comment by mpirogov** [comment]
please hope review

**Comment by trntv** [comment]
merged. thank you
