### ISSUE TITLE
Question regarding Logging

### ISSUE THREAD

**Issue by Bhoft** [trntv/yii2-command-bus#5]
Hi i am testing out your extension yii2-command-bus.

So far everything works fine. 
On the first tests I thought that I don't have to wait for the process when using Background commands with symfony but the Queued fulfilled my requirement to execute external code independent on the page rendered.

I wanted to sent e.g. 1000 email via a background process.
The process is now running with your command bus extension and an queued Command like this:

```
class SendQueuedEmailsCommand extends Object implements SelfHandlingCommand, QueuedCommand
```

My question regarding your extension are:
- How can I log the job status (e.g. running, successful, failed) and also log the "result" or the output of my job e.g. in my job how many emails were successfully sent or failed to sent.
  I really would like to add an entry to the database table with the job id and that the result and status is updated on change. So I could have an ajax action which shows the status of the running job or have an controller to just list the scheduled jobs and their status + result.
  I looked into other extension which implemented PSR-3 Compliant Logging e.g. https://github.com/chrisboulton/php-resque/pull/115/files

If you have an example how to log the job status and result with your extension I would really appreciate this. 
- Another thing I detected that i have to restart the background console command every time i made changed to the job class. If I not restart the process the code will just run with the old and not the changed code.
  Is that a normal behavior and can this be changed somehow?

**Comment by trntv** [comment]
1. Database entry is the best solution for this case. I usually use redis for such purposes, but it can be mysql or any other db.
2. Yes, this is normal behavior for php script, but you can try to use [pm2](https://github.com/Unitech/pm2) with `watch` mode enabled

**Comment by Bhoft** [comment]
regarding 1. and how can i access the result or attributes of the job?

I tried to access the job object in e.g. QueueBusController::onSuccess but the attributes of the unserialized Job object are always the default ones e.g. null and don't have the values which are set when the job is executed.

The $result in QueueBusController::onSuccess is of course the return value of my command and could be stored in the database.
But attributes which are changed during the execution of the command are still not changed.
For me it looks like that the CommandBus or QueuedCommandMiddleware don't use the job object by reference so that the attributes aren't changed.

Can you give an example on how do you log the process changes on different events.
What I tried is the following 

```
'queue-bus' => [
       'class' => 'trntv\bus\console\QueueBusController',
       'on '. trntv\bus\console\QueueBusController::EVENT_BEFORE_HANDLE => ['handlerClass', 'handleBeforeHandle'],
       'on '. trntv\bus\console\QueueBusController::EVENT_AFTER_HANDLE => ['handlerClass', 'handleAfterHandle'],
    ],
```

with a function like below

```
class handlerClass{
....
public static function handleAfterHandle(QueueBusEvent $event)
{
    $id = ArrayHelper::getValue($event, 'job.id');
    Console::output("event after Handle ID#{$id}");

    $job = ArrayHelper::getValue($event, 'job');

    if (array_key_exists('serializer', $job['body'])) {
        $unserialize = $job['body']['serializer'][1];
        $command = call_user_func($unserialize, $job['body']['object']);
        var_dump($command);
        var_dump($command->failure);  // null and not the changed value
        var_dump($command->success); // null and not the changed value
    }
}
....
}
```

and failure, success are attributes in my Command which I change on execution.
And as i have written if i add similar code to QueueBusController::onSuccess the attributes are also null and aren't the changed values.

**Comment by trntv** [comment]
There is no **command** object in onSuccess or onError handlers there is **job** array. Job is something coming from queue. 
If you want to log something from command you should log it inside command execution or you can use middlewares. They have access directly to `Command` object.

I think i should create something like `LoggingMiddleware` for example.
