### ISSUE TITLE
can you give a selfhandled redis queue command example?

### ISSUE THREAD

**Issue by gouchaoer** [trntv/yii2-command-bus#7]
i really got puzzled...

**Comment by gouchaoer** [comment]
i mean how to push the comman into redis, your example is a background commod

**Comment by gouchaoer** [comment]
public function handle($command)
    {
        $chain = $this->createMiddlewareChain($command, $this->middlewares);
        return $chain($command);
    }

this method in CommandBus which is called in QueueBusController, will push the $command into the queue again if the QueuedCommandMiddleware is setted in commandBus component, which is wrong.

**Comment by gouchaoer** [comment]
i finally figure it out...
actually a selfhandle command will handle itselt twice, one time in the yii2 web controller, one time in the yii2 console controller(either queue or background type). so in the handle method in command， user have to check $this->isRunningInQueue() to decide if to do the real job. i think this is puzzling. i take a lot of time to understand this.

**Comment by trntv** [comment]
But it keeps CommandBus from violationg SRP :-)
It's responsibility of corresponding middlewares, so `isRunningInQueue()` is the only way to handle it.
