### ISSUE TITLE
DelayedCommand feature request

### ISSUE THREAD

**Issue by AnatolyRugalev** [trntv/yii2-command-bus#8]
Hi, first of all, thank you for extension.

I use RedisQueue and self-handling commands, and they're great, BUT I need to set custom delay for some kind of commands. Now I have to temporary change `$delay` property of `QueueMiddleware`, and this is not great. May be we could make some kind of `DelayedCommand` with `getDelay()` method?

**Comment by trntv** [comment]
We also can extend existing QueuedCommand interface but this is ВС breaking change. I'll try to find best solution for this new ability.

**Comment by AnatolyRugalev** [comment]
@trntv Thank you!
